spring:
  cloud:
    nacos:
      config:
#        shared-configs: application.properties,common.properties
        refresh-enabled: true
        server-addr: 127.0.0.1
        file-extension: properties